openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/cars/correct/:
    get:
      operationId: listGoodCars
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateGoodCars
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    put:
      operationId: UpdateGoodCars
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyGoodCars
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
  /api/v1/cars/incorrect/:
    get:
      operationId: listBadCars
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateBadCars
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    put:
      operationId: UpdateBadCars
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyBadCars
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
  /api/v1/trucks/correct/:
    get:
      operationId: listGoodTrucks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateGoodTrucks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    put:
      operationId: UpdateGoodTrucks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyGoodTrucks
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
  /api/v1/trucks/incorrect/:
    get:
      operationId: listBadTrucks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateBadTrucks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    put:
      operationId: UpdateBadTrucks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyBadTrucks
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
